language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer  

install: true

# define the order of the stages:
stages:
  - test

script: mvn -Prelease -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true

env:
  global:
    - MAVEN_OPTS="-Xmx2g"


cache:
  directories:
  - $HOME/.m2