language: java
dist: trusty
jdk: oraclejdk8

env:
  global:
    - MAVEN_OPTS="-Xmx2g"

script: mvn -Prelease -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true

cache:
  directories:
  - $HOME/.m2