language: java
jdk: oraclejdk8
dist: trusty
addons:
  apt:
    packages:
      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259

install: true

# define the order of the stages:
stages:
  - test

script:
  - mvn install -B -DskipTests && cd ${TRAVIS_BUILD_DIR}/${MODULE} && mvn failsafe:integration-test failsafe:verify -B -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end

env:
  global:
    - MAVEN_OPTS="-Xmx2g"


cache:
  directories:
  - $HOME/.m2