
name: test

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#  pull_request_target:
#    branches:
#      - master
#    types:
#      - closed


jobs:
  build:
#    if: github.event_name == 'push' || github.event.pull_request.merged == true
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout git repo
      uses: actions/checkout@v3
        
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
        server-id: ${{ github.event_name == 'push' && 'matsim-snapshots' || 'matsim-releases' }} #choose mvn repo
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        
    - name: Build jars
      run: mvn -B package --file pom.xml
  
    env:
      MAVEN_OPTS: -Xmx2g
